hostname: bigbang.dev

flux:
  interval: 1m
  rollback:
    cleanupOnFail: false

gatekeeper:
  values:
    replicas: 1

istio:
  values:
    kiali:
      dashboard:
        auth:
          strategy: anonymous
    ingressGateway:
      serviceAnnotations:
        # Ensure mission apps have internal load balancer only
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
        # Enable cross zone load balancing
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

monitoring:
  grafana:
    enabled: true
    grafana.ini:
      server:
        # The root URL must be set with the proper url to enable oauth login
        root_url: https://grafana.bigbang.dev/
      auth:
        # URL to redirect the user to after sign out
        signout_redirect_url: https://login.dsop.io/auth/realms/baby-yoda/protocol/openid-connect/logout
      auth.generic_oauth:
        enabled: true
        client_id: $__file{/etc/secrets/oauthinfo/client_id}
        client_secret: $__file{/etc/secrets/oauthinfo/client_secret}
        scopes: Grafana
        auth_url: https://login.dsop.io/auth/realms/baby-yoda/protocol/openid-connect/auth
        token_url: https://login.dsop.io/auth/realms/baby-yoda/protocol/openid-connect/token
        api_url: https://login.dsop.io/auth/realms/baby-yoda/protocol/openid-connect/userinfo
        allow_sign_up: true
        role_attribute_path: Viewer
    extraSecretMounts:
      - name: oauthinfo
        mountPath: /etc/secrets/oauthinfo
        secretName: grafana-oauthinfo
        defaultMosde: 0440
        readOnly: true

logging:
  values:
    elasticsearch:
      master:
        count: 1
        persistence:
          size: 5Gi
        resources:
          limits:
            cpu: 1
            memory: 3Gi
      data:
        count: 1
        persistence:
          size: 5Gi
        resources:
          limits:
            cpu: 1
            memory: 3Gi

twistlock:
  values:
    console:
      persistence:
        size: 5Gi
