hostname: bigbang.dev

flux:
  interval: 1m
  rollback:
    cleanupOnFail: false

# Gloabl SSO parameters
sso:
  oidc:
    host: login.dso.mil
    realm: baby-yoda
  client_secret: ""


addons:

  gitlabRunner:
    enabled: true

  gitlab:
    enabled: true
    hostnames:
      gitlab: gitlab.bigbang.dev
      registry: registry.bigbang.dev
    sso:
      enabled: true
      label: "Platform One SSO"
      client_id: "platform1_a8604cc9-f5e9-4656-802d-d05624370245_bb8-gitlab"
      client_secret: ""
    # database:
    #   host: postgres-postgresql-headless.postgres.svc.cluster.local
    #   port: 5432
    #   username: postgres
    #   database: postgres
    #   password: postgres
    # objectStorage:
    #   type: minio
    #   endpoint: http://minio.minio.svc.cluster.local:9000
    #   region: us-west-1
    #   accessKey: myaccesskey
    #   accessSecret: mysecretkey
    #   bucketPrefix: kwilder
    # objectStorage:
    #   type: s3
    #   endpoint: https://s3.amazonaws.com
    #   region: us-gov-west-1
    #   # accessKey: myaccesskey
    #   # accessSecret: mysecretkey
    #   bucketPrefix: kwilder
