hostname: bigbang.dev

flux:
  interval: 1m
  rollback:
    cleanupOnFail: false

gatekeeper:
  values:
    replicas: 1

istio:
  values:
    kiali:
      dashboard:
        auth:
          strategy: anonymous
    ingressGateway:
      serviceAnnotations:
        # Ensure mission apps have internal load balancer only
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
        # Enable cross zone load balancing
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

logging:
  values:
    elasticsearch:
      master:
        count: 1
        persistence:
          size: 5Gi
        resources:
          limits:
            cpu: 1
            memory: 3Gi
      data:
        count: 1
        persistence:
          size: 5Gi
        resources:
          limits:
            cpu: 1
            memory: 3Gi

twistlock:
  values:
    console:
      persistence:
        size: 5Gi

addons:
  anchore:
    git:
      branch: main
      tag: null
    enabled: false
    values:
      postgresql:
        image: registry1.dsop.io/ironbank/opensource/postgres/postgresql96:9.6.18
        imagePullSecrets: private-registry

      anchoreGlobal:
        image: registry1.dsop.io/ironbank/anchore/enterprise/enterprise:2.4.1
        imagePullSecretName: private-registry

      anchoreEnterpriseGlobal:
        image: registry1.dsop.io/ironbank/anchore/enterprise/enterprise:2.4.1
        imagePullSecretName: private-registry

      anchore-feeds-db:
        image: registry1.dsop.io/ironbank/opensource/postgres/postgresql96:9.6.18
        imagePullSecrets: private-registry

      anchoreEnterpriseUi:
        image: registry1.dsop.io/ironbank/anchore/enterpriseui/enterpriseui:2.4.1
        imagePullSecretName: private-registry

      anchore-ui-redis:
        image:
          registry: registry1.dsop.io/ironbank
          repository: opensource/redis/redis6
          tag: 6.0.4
          pullSecrets:
            - private-registry
