hostname: bigbang.dev

flux:
  interval: 1m
  rollback:
    cleanupOnFail: false

gatekeeper:
  values:
    replicas: 1

istio:
  values:
    kiali:
      dashboard:
        auth:
          strategy: anonymous
    ingressGateway:
      serviceAnnotations:
        # Ensure mission apps have internal load balancer only
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
        # Enable cross zone load balancing
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

eckoperator:
  enabled: false

fluentbit:
  enabled: false

logging:
  enabled: false
  values:
    elasticsearch:
      master:
        count: 1
        persistence:
          size: 5Gi
        resources:
          limits:
            cpu: 1
            memory: 3Gi
      data:
        count: 1
        persistence:
          size: 5Gi
        resources:
          limits:
            cpu: 1
            memory: 3Gi

clusterAuditor:
  enabled: false

twistlock:
  values:
    console:
      persistence:
        size: 5Gi

addons:
  anchore:
    git:
      branch: main
      tag: null
    enabled: true
    values:
      #sso:
      #  enabled: true
      postgresql:
        enabled: true
        image: registry1.dsop.io/ironbank/opensource/postgres/postgresql96:9.6.18
      anchoreGlobal:
      #   oauthEnabled: false
        # saml:
        #   secret: sso-secret
        image: registry1.dso.mil/ironbank/anchore/engine/engine:0.8.1
      # anchoreEnterpriseGlobal:
      #   enabled: false
        #image: registry1.dsop.io/ironbank/anchore/enterprise/enterprise:2.4.1
      # anchore-feeds-db:
      #   enabled: false
      #   image: registry1.dsop.io/ironbank/opensource/postgres/postgresql96:9.6.18
      # anchoreEnterpriseUi:
      #   image: registry1.dsop.io/ironbank/anchore/enterpriseui/enterpriseui:2.4.1
      # anchore-ui-redis:
      #   enabled: false
      #   image:
      #     registry: registry1.dsop.io/ironbank