hostname: bigbang.dev

flux:
  interval: 1m
  rollback:
    cleanupOnFail: false

gatekeeper:
  values:
    replicas: 1

istio:
  values:
    sso:
      enabled: true
    kiali:
      dashboard:
        auth:
          strategy: anonymous
    ingressGateway:
      serviceAnnotations:
        # Ensure mission apps have internal load balancer only
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
        # Enable cross zone load balancing
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

logging:
  enabled: false
  values:
    elasticsearch:
      master:
        count: 1
        persistence:
          size: 5Gi
        resources:
          limits:
            cpu: 1
            memory: 3Gi
      data:
        count: 1
        persistence:
          size: 5Gi
        resources:
          limits:
            cpu: 1
            memory: 3Gi

fluentbit:
  enabled: false

eckoperator:
  enabled: false

monitoring:
  values:
    sso:
      enabled: true

twistlock:
  values:
    console:
      persistence:
        size: 5Gi
addons:
  authservice:
    enabled: true
    values:
      chains:
        kiali:
          match:
            header: ":authority"
            prefix: "kiali.bigbang.dev"
          client_id: platform1_a8604cc9-f5e9-4656-802d-d05624370245_bb8-kiali
          client_secret: secret
          callback_uri: https://kiali.bigbang.dev/login
          cookie_name_prefix: hello_world
          logout_path: /logout
        prometheus:
          match:
            header: ":authority"
            prefix: "prometheus.bigbang.dev"
          client_id: platform1_a8604cc9-f5e9-4656-802d-d05624370245_bb8-prometheus
          client_secret: secret
          callback_uri: https://prometheus.bigbang.dev/login/generic_oauth
          cookie_name_prefix: hello_world
          logout_path: /logout
        tracing:
          match:
            header: ":authority"
            prefix: "tracing.bigbang.dev"
          client_id: platform1_a8604cc9-f5e9-4656-802d-d05624370245_bb8-jaeger
          client_secret: secret
          callback_uri: https://tracing.bigbang.dev/login
          cookie_name_prefix: hello_world
          logout_path: /logout
        alertmanager:
          match:
            header: ":authority"
            prefix: "alertmanager.bigbang.dev"
          client_id: platform1_a8604cc9-f5e9-4656-802d-d05624370245_bb8-alertmanager
          client_secret: secret
          callback_uri: https://alertmanager.bigbang.dev/login
          cookie_name_prefix: hello_world
          logout_path: /logout

  haproxy:
    git: 
      repo: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/haproxy.git
      path: "./chart"
      tag: 1.1.2-bb.0
    values: {}

