hostname: bigbang.dev

flux:
  interval: 1m
  rollback:
    cleanupOnFail: false

clusterAuditor:
  enabled: true

gatekeeper:
  enabled: true
  values:
    replicas: 1

istio:
  values:
    kiali:
      dashboard:
        auth:
          strategy: anonymous
    ingressGateway:
      serviceAnnotations:
        # Ensure mission apps have internal load balancer only
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
        # Enable cross zone load balancing
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"

logging:
  enabled: true
  values:
    elasticsearch:
      master:
        count: 1
        persistence:
          size: 5Gi
        resources:
          limits:
            cpu: 1
            memory: 3Gi
      data:
        count: 1
        persistence:
          size: 5Gi
        resources:
          limits:
            cpu: 1
            memory: 3Gi

monitoring:
  enabled: true

twistlock:
  enabled: true
  values:
    console:
      persistence:
        size: 5Gi


eckoperator:
  enabled: true

fluentbit:
  enabled: true

addons:
  minioOperator:
    enabled: true
  minio:
    enabled: true
#    accesskey: lynnio
#    secretkey: lynnpassword
#    values:
#      nameOverride: lynnio
#      service:
#        nameOverride: lynn-svc-override
#      istio:
#        virtualService:
#          enabled: true
#          name: myminio
#          hosts:
#          - differentname.bigbang.dev

