apiVersion: v1
kind: Secret
metadata:
    name: environment-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:Q8NCcqJMX2JBBsPf7moA2taQYPbTIh2xk0qKVCGf+v3jmX9O8gdoZm7bKCIY8uXfloe3yOSXwTc3khjuZYns1JbIXOyf37+6dN6ORTDj6WRU+07IyRBIWH+NdiJcR64t7ShGobs+s+ImzZsbDQ+WxtG+IPBTagQG2+mP2EY08MlPjrvQlwnT9w5VGHlJqnDOdoYweKWNaiPRyK43lnyZ6S+pwmnsm3FSX8uRFiDKEo9ZK4vWXWTnG5jLn4X2KElPt11TnVDr/Mzn3ml8np8RcgYGv719ztlsWRllVtXHoDT65LlJHOu2p0sPBbgK8bs/cvLHS6zFy1TFLIn0cyWoMA8aA8NNwjktBMnkYgoZSw==,iv:AFNAIGDDsjPAbLi9cEQiCu4/y8hIjZW72+iTUxGnFFQ=,tag:jg57ZHBCWGBmOfe1/5/G0A==,type:str]
sops:
    kms:
    -   arn: arn:aws-us-gov:kms:us-gov-west-1:927962728993:key/f131e19c-a804-4185-b75f-69b995eb9e6a
        created_at: '2021-01-06T17:20:00Z'
        enc: AQICAHiBokhIqRyovOZILp3cL4ZLeOMUIKZsOV08m7PNyQevrgG908T7Vq8GUEF5lJtQRoAkAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMHM0E+/3e3Hjmbnr7AgEQgDtf+iNyDNcvj6Wk8maaNzjAzO6EDebbcPUUSiS6WsOliaKjoMCZp/fXvGBrWk5GsazzJ5eTBnzfhLh2xg==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-01-06T22:18:52Z'
    mac: ENC[AES256_GCM,data:ixxoXV6+cxqE/ZkysdyH/J7NX96+B2LMsR8QTHEKkd4fN/QgjhEzXXUVDgPbMzvvry3si/yy7Z0kygFwe48ekpmAfnvc427qD1zBLsjbiM4HB43xtQNmNc+q6hRGSTWD3BGSRc/DwzS83PUMYyOljrFrI/LskIrr22TebnXBhG4=,iv:1dlasI3BKFD0FKQbBt4JQhNSA+Xz5CHVDhzllwjsVCs=,tag:rmqHzK+xuM+ilgUbza5mVA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
