apiVersion: v1
kind: Secret
metadata:
    name: environment-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:MH+Gf3bIZKLodxOMLi9vqcyqwaH6Kr6ABoBN/zAYojfU11pD+NZQ6AzUynIF22xNVlFEFVICvBAyi39WeA1tr0y33wEczHFqp9IaKXeBo8ubtVsqHdYcO3ZXujZoD27YoeHlHt9AHTJfGATYHGr9SY6fbcTPe4J0ZKIOSwGSu3O/fsr1kj8QJ/a5FgdLMA4flfqKAoJ3ZvoyKa/6k9GYQZkyUtKRfBJv9iGmNnwctGUByr3nFw4dZoQp+HwBDoh6McbIq0BTIm2POb4GMjKF1YNFRnRYpWqabGYDpUMafMV2BPHGaHdqiYCRyxeOvscMaHleiShrI7gLsfapAAk6ctRSz+U=,iv:nX75xTiAIgLOSjq/VGDsnAkthGvHGyZ38mE5FmYYwug=,tag:tBgnv//yh0LLi3zh+PWBcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-02-26T22:40:03Z'
    mac: ENC[AES256_GCM,data:1lLbCA/YxjvWk2WZbtzcJFY2WUHhO8fHVnRXuJt83Q9A7uB8H4ExFMdM+627DaiHQXi36mfNff6WHUikwnRCKPqZ6dhU13B8hfvzCizs8JdY0gb/PlVdvKSWTGlSon0MGVcqZ8ZKWhwlZHwtvMNrwdt4xZYgCQNjpW+poSVjgus=,iv:5AXuNXiLAe+rn5tIbOTX+ZpzOSDMlyu6mHN9t0xKQUg=,tag:RhcxlkRGRXhYrC9qzr2ocg==,type:str]
    pgp:
    -   created_at: '2021-02-22T20:51:54Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3z9hfqYdVrXAQ//Us5AYIE5G2xo+kdiYA8k+reTEkXM7GyPchRw5vjNk1vU
            n09LUe9nsplPOifNodGIu0r+C/CKFpx45BmMBkRiYeD/O0Xi4ggl+BFjTxwlynrh
            tBAMryu/iZeHFTEYzqVEDxqltX0et6l5pz3oXik3oGrQ/3cXBweSrEUqfOUVkBlw
            +d2akMFiOb4w5yJT04W0EcUggoiFCUtODPa82WnqoxW+MklFbnxap87nMg8n1BXm
            jWW58HySABGs6b9g2lR/wKJIDw6hj7TRXApnITnOLWBgRtQvXzVjhdrs3keCGfgi
            X6RAzkEjh1GCpFI/FMBaa2wrwNOGbopbDpe+Ayt/O5xc1AyLRrGIlX1hYYE8pKz+
            eSCcNdSy2u9tIk6uKNtcEZ5iZg5ndofwg2EenGG1uudH+5CjSFHOtfMldRWZTOBE
            Vw60tyDlze+3P1viKt8SdMna0vkIDOnfhyXJZ27u7ErzKPz5r/ioj7gwLJN309Pp
            34dMRcUFIobxMdYM3zwzGvtCpQbg8ZHikmFsFjwk0gZyWpryczrGGq8YcSzPIE6L
            uX20wt82hyZHYhw5ob1VK46k9t8El3EowoX2uFLFepKzsgYxp96MB0WL5G+xLjMD
            +UfFcxhCLGk5ayfmRR2RbivvF2e55NQtdWK5aQNuvOJK8WRHkUGTzzdiGfMCzNLS
            XgGMwtQc5X+4LN625KttCc/yz94wgHmq3x+3ROh7Zxg66RbCzkilyyzoVRPR1QhE
            vCeCkc2uJoC+j8Oytzqt7LmzUWtkXd1eR4en48gUqbeLic2iw9VKMS0QR6LR9TQ=
            =n7xF
            -----END PGP MESSAGE-----
        fp: F81A64A7A0B46155B2D48C1876C82046B62EC9A1
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
