apiVersion: v1
kind: Secret
metadata:
    name: environment-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:NljTOJZECQ6kCg==,iv:Tl2VZmgSS7qEbD54TAEKUdC3hEtNEbbLHbeFTFp71kM=,tag:30Kg4V3upGNyyuk0PNApGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-01-29T20:46:03Z'
    mac: ENC[AES256_GCM,data:yIuIikLkw7aC7Z/SaE4cT7ntBt5po+AFuHoh1HU5gop4hiy4F90vM9DQu0Bayy8a74z/u7shJuefHvX5qRW9Ib4YTClWPGRzu8Asi4dwGhwK/drDjma7h8IFMD3qKG+ren7st5hrNx7zpuVFm5xsTe5ywFna36Tyain/bmqfKQE=,iv:Qi/Wx3WUluNNPQyLxG+mbS7cEAm1eTD66RXT/1Joq1E=,tag:UxMbUAJLsdHD1C5mE4mNzA==,type:str]
    pgp:
    -   created_at: '2021-02-03T21:50:36Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx4+MHbVV2OiAQ/+Jv5m0kTxzJ18a6LqyOHIPM5sQl9IpxJHOBfS5bobr96O
            WbRYMHkO6cA4HX4SGtIVnV1Jkg/YNHwO+3pQOELdqNOq9DBPbFqNIIVtXMBlBDCQ
            uKY0ifeDSmbrZNd9WyBXshTH62v3qxU+ld7fORGedATmGnvWSFo3obzcEevu2Sf8
            7tH2+BwqI3aIB/XNDQ5xaet7+nZwzv6yZN0B3LL0na5qU7l5qe3b5aUv+8GhBWyn
            gfh5h3x0g1VLvCa3JShRjORbxGNfuvcLU//nbLLVBTQqWBy8z1H1DQymi1OcrqXm
            BYL7zHa9PTZVhoOMKsAi7UhC8hAvSEnoAx/NFu/p/ffFaumtq1IvIanRr7NuQ4a0
            XPpwZJvatAxxDpyFnMs3D9C/kPMtPP2rOauykOl6kPa6y9mhDTtvCyhCJvr3byYU
            LL7MF7u+HZ/PO9HvC2I57KBwgiQCPFNB3fdyfe3GDmkrTIX9HOyeTw1qI5QahHJ9
            OF9uEAsqoYIapolTsoTqWAvXKkL1QI8CdX7Ek1NgSYp0UpBtxk7C+Dd5GFlfKZ4H
            KGSMU8jud7POsi7tXS/WJng9ex8gRP5zXeGMPsakz3NZHXijLw/efi8PxmgqgsVb
            X5Uupkoc2/NKx+1BI6fljdmzIgVaY65fFvGzy13oKzq9Juu7t5kdAxG7dDIZ8AHS
            XgEM5yUvLuz9G51EAOaN6/dUSBlqs49Ft8El86SJL6PdQbz+JJxxWuCQA3NNaBsu
            bvo1a1agXHg8B2SiFgHxku6GgSK1whuq7Bxn6cgEyFHWvV2RjnU5ywHgsQ2nG9Y=
            =ISaP
            -----END PGP MESSAGE-----
        fp: 4F7B17D8DC0EB7F9B21AB8E484F38067748779D5
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
