apiVersion: v1
kind: Secret
metadata:
    name: environment-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:6BFdMgLCBK6Z9CnlnsfSdEJ6MXMRbUhdDtPw7sc7dFim45BCgkPnprp0Hz4h4b1gk5EGFSgfBJBPvfWRMD1wsoegwT7SOVYFvImjjPvaVBG343pnXxaMTfAiCBftHW2ulbIoVUyO0qNHZ4ZTjB6FV1YG3EgrNJBhM2Hz26u5oIKuDlqvEN88T0lUu5bjQExFvw6/Xv+XrjQz4uE46Jt4NWsJyvvooJkhbKcgjAOgysdcCFhqla7smMo3TVjC+EWAHfTnR70JirlBY0OlZp7trdRYvM6wB194LSOtI9bXvr+0Ewez1Ggd4Od3XVpYRjrMeNbmYHCEVw6gCBUtaS8EQlIwg83lgg==,iv:MAeD8RY8zCEy/loB8HZukiKqi6brZ5aLt0yTEoqKRbY=,tag:MDTVMrQ9vXAfINS9tRFcNQ==,type:str]
sops:
    kms:
    -   arn: arn:aws-us-gov:kms:us-gov-west-1:927962728993:key/f131e19c-a804-4185-b75f-69b995eb9e6a
        created_at: '2021-01-06T17:20:00Z'
        enc: AQICAHiBokhIqRyovOZILp3cL4ZLeOMUIKZsOV08m7PNyQevrgG908T7Vq8GUEF5lJtQRoAkAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMHM0E+/3e3Hjmbnr7AgEQgDtf+iNyDNcvj6Wk8maaNzjAzO6EDebbcPUUSiS6WsOliaKjoMCZp/fXvGBrWk5GsazzJ5eTBnzfhLh2xg==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-01-06T23:57:26Z'
    mac: ENC[AES256_GCM,data:NqJbfWqi0vdHnIRDtlaUGBAdi1OKBcvwwRHnJX0PsX5suKTQniHOrNJ4kjFmVkdO3kCQiTCkE+CwF8qK8f9iU4/Glb9tuZhjp49NlSO+uQ+KFCbiveY4AesCYBemIcEneRqPqltyFlGeExFUypdeLyXO0qSMGd/uhXhdqM1t5/4=,iv:v7cSoF6mvXPp0eZRR93YFKR7vXOGlbRnQTeEquCJ0jY=,tag:2GVu61lHemVEOqE39AcwCg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
