apiVersion: v1
kind: Secret
metadata:
    name: environment-bb
stringData:
    values.yaml: ""
sops:
    kms:
    -   arn: arn:aws-us-gov:kms:us-gov-west-1:927962728993:key/f131e19c-a804-4185-b75f-69b995eb9e6a
        created_at: '2021-01-08T21:36:43Z'
        enc: AQICAHiBokhIqRyovOZILp3cL4ZLeOMUIKZsOV08m7PNyQevrgEwmp1UZHxLjm67sA1Xa/zGAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMz5UeNhHA/ht2b/XoAgEQgDvFjQT8IavOqqAxOpZxjJLv1qLblDNdgjclQpEN3ta72I53nBoFtIjgVgoBPvgvIsAs1C+sg38fNSDyWg==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-01-08T21:36:43Z'
    mac: ENC[AES256_GCM,data:Etwvu8GR6zNGHOWHuREtG0G/JJd+qb2nISOhd4xWSRjz5Cxl57GazvsgOSrl98WzOq//aa/KXJQ+cbWkrB+QZZGYOkAk48Z+bBjuEb4SBmFltHwgNmmxXKIN29zeUE5DkA3W212zC97NjRCNrNzX7SeQtviokJOhPCF6nd/c29A=,iv:XO15XI9RsxLqv8dkNTpyPy4IEZELgxoWYSOdyIzhHA4=,tag:h0svviXWPqHmefwRRaVFog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
