apiVersion: v1
kind: Secret
metadata:
    name: environment-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:NljTOJZECQ6kCg==,iv:Tl2VZmgSS7qEbD54TAEKUdC3hEtNEbbLHbeFTFp71kM=,tag:30Kg4V3upGNyyuk0PNApGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-01-29T20:46:16Z'
    mac: ENC[AES256_GCM,data:E6WnvTwFjOkYQHilXbepEDd6NAMNbkmLOjD3TW3Xve/KR//xS9d2W0ktaV2TGgYwc//2w5c1QW14bO21QSvn+Nr9vTB3M2s684pUPCcDo+febWxAyg8Wm8tvUEqY+nTzVkL1xou0cdYlirSWuw3TxATrcni99taL7wWIXXWEQ1Q=,iv:gQVrJO41j6pfCF1+93tLS0f5gMHforUEmF9jlq3Fd9I=,tag:TGH5gjjgLZZBq6EnfH4XYg==,type:str]
    pgp:
    -   created_at: '2021-02-28T16:40:56Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4xPVzD2BiIcARAAiYeKHdOpFeJcbjh7UoImmsaMHYjPX5fDrmqYjXqO/N6H
            TMr/xlgQOL7jQnUXvFkDTeCoeZL0vDx3hQkIPazj+DUbv47OMVunpFBVHpcsgww5
            AtoZkb+a5IRG0tEaCLMapApuxnasUIu5PnSoA0Aoj/Z9aYUsr9syWj6m+5o1IxuG
            RRT1cu+JQKT3Ps8vhDUek6/M2MDaMsKkqzKL8dmUlS9rJ2aE83u73lXwWgBNLR7P
            xiv9bHfp/q4UIWURw3vI9k8/d7GhoN00qaN6EjQt4r3RgEAPKt4lYCYH4PaiwaVs
            oyrQZtFpqypXcHiRKvxezQz5dVWs7VQf5WfL+0rvEfuHzaRHh5ApjbWEKhqz0YuS
            LTiqKdQmNjqepJdQ//cuD2IHIHzjhU8GePnP7rRoS6wyHru2pUFI/Of1yykqbp3Y
            Xx46yCWwngwSPsQ4NtNFMPKztwsK5gqvvAvSYnJcu30+56waPbL3DHQ0ipkxisHE
            be59SGMSNV0emeQPdzUf4bg91q3ouJ4VfgQUmNu98Z3axNG4wgzwpdKqkl3QaXzI
            A+EHZ/KkGXIxrBOqkeg5nJCpiULMZ8UURS6SaIUWv71aQf2J7VwFPay07xBAw0Yz
            IBU4sOIEvf4cwl/UOSr+DqGyCyaZ6eufQL/5aSgqyBa3dFbAIf/b9hNZXyRL11/S
            XgEJuxO6Lm4ThM+leILHTXOy7oY3+/WtcqFhB8gy/gD8sABWzFGA6ZSNqvxCplcU
            XcD4w3Vo0mq5OW9Nb5sVXpA9UQCfQVeaol4s6ZTz4EF7IHLl+QRTCb04vqnUZCE=
            =URG+
            -----END PGP MESSAGE-----
        fp: FDD6838CB1313C5867AE113612AF849E59E1F0A5
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
