apiVersion: v1
kind: Secret
metadata:
    name: environment-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:NljTOJZECQ6kCg==,iv:Tl2VZmgSS7qEbD54TAEKUdC3hEtNEbbLHbeFTFp71kM=,tag:30Kg4V3upGNyyuk0PNApGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-01-29T20:46:16Z'
    mac: ENC[AES256_GCM,data:E6WnvTwFjOkYQHilXbepEDd6NAMNbkmLOjD3TW3Xve/KR//xS9d2W0ktaV2TGgYwc//2w5c1QW14bO21QSvn+Nr9vTB3M2s684pUPCcDo+febWxAyg8Wm8tvUEqY+nTzVkL1xou0cdYlirSWuw3TxATrcni99taL7wWIXXWEQ1Q=,iv:gQVrJO41j6pfCF1+93tLS0f5gMHforUEmF9jlq3Fd9I=,tag:TGH5gjjgLZZBq6EnfH4XYg==,type:str]
    pgp:
    -   created_at: '2021-02-03T21:50:48Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx4+MHbVV2OiAQ//YgaFZYXEjFfQGFRpGVgiFfI8Ae/zg7iH90D15wKrRYZe
            IL4aVF6dverRECwTj+t0G+24Z2Z/ZFCcJ+xCwmACyMKARYGP214+SrNfOj265nx2
            bfuBmOKepM5Qbagl7blHHJEHK/0yZzLYvVCfUKQ+cf8ndVsz6OZNsrcdxIBmWm3E
            sHpk2jZivbTY+eRTkY0mNYKg94RjCIdNkPDoLKBGY9VcIQSLmWme8eNhjTwaDCAv
            92kq8MkijSeyyBKWG1rdDCo301iSfhWv/9IU3n1ci1b24oPxnG75aN5johJR9sfY
            JNaALUszdNngjpN00y1qG5q4JJCYjjDDJjSkRBXxQAjSN+8Co0bEbA0XLxgtT90k
            EVITSU+kxN6c7ETfsEV8psxCGT+bsEDUaBlSDqkEJb6j35oPwyON9hDgMXfTpVvn
            /hW46kyH+JsGW94osQOiEga30iDZyuBLZFK/njHfqE5sCvJZv4TuhvPudGn+/7Hd
            TEao7bW0CztSajq4HHMhmA/r/Xqg8TaH6Ch9LShLH1CKTXNyWUAVZEVWY5Rnj7gx
            S1P38gC+ESNhRhvJy8k85Tihd//nI9GFvG2zZrj+7mwft95xhDmjBlzuRvZsaYm7
            AScxAplfoJh/mUjNm+Ys1Agb1rhAGoEVqKRPbxwSihySsL3jYmz9D42tEvfK7F/S
            XgG8eBYSGIKYTt0ZCovsguoWGLOOe/wtsG5SP1susEQ//EDxPWuoJ/7+oPZ/ZM/a
            zPHYw1Ukn0MI2iEJTpwFUbkZEe9CQ/Wr/Mr5gi4+2K6VQF/uDtisnk5xI28gqB4=
            =RMW0
            -----END PGP MESSAGE-----
        fp: 4F7B17D8DC0EB7F9B21AB8E484F38067748779D5
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
