hostname: bigbang.dev

flux:
  interval: 1m
  rollback:
    cleanupOnFail: false

clusterAuditor:
  enabled: false

gatekeeper:
  values:
    replicas: 1

istio:
  values:
    kiali:
      dashboard:
        auth:
          strategy: anonymous

logging:
  enabled: false

monitoring:
  enabled: false

twistlock:
  enabled: true
  values:
    console:
      persistence:
        size: 5Gi

addons:
  argocd:
    enabled: true
  gitlab:
    enabled: true
    sso:
      enabled: false
  gitlabRunner:
    enabled: true
