hostname: bigbang.dev

flux:
  interval: 1m
  rollback:
    cleanupOnFail: false

clusterAuditor:
  enabled: false

gatekeeper:
  values:
    replicas: 1

istio:
  values:
    kiali:
      dashboard:
        auth:
          strategy: anonymous

logging:
  enabled: true
  values:
    elasticsearch:
      data:
        count: 3
        persistence:
          size : 20Gi

monitoring:
  enabled: true

twistlock:
  enabled: true
  values:
    console:
      persistence:
        size: 5Gi
