apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:UuUpLor+dtNbrVzIHzx1lta4h89p6IrZfZhtmPYTCNMwQi0S36ERQodK9bFRdKY61KUlzoBWRMWNh0z0CECV26qg4b3gDBPez/uAVQP89Au27fKUGSWPjbmUbqS/QVklqTqsPowCpGobQ34CWK1yPkXqhCXL/utLmpkeQM3RpQjKIFCclvXJqQ00R1qTr/Ai5LhuMEzzqQJx/xAJ5Rqyo3xz5J7SCneSJGFC/Tz79U0cHRV92dtTdcdCMmC9q0kk6TQM5KzIhofPZDLBG/5Q+AAXvXib2y6ZxWcFig9fcugt9Uk8rtQpBcTKWnIIGy9ydpgZ3khnGQQatq0/7FAJpKAXLX+GfdOWB7y747SVPOyjz495RZHBZywav/MBPSjRMupOOGNPXITSN8xbOfTkFh1aF9d+1WwqdhMGKpe0JujzUXVKGc5MilAWyo+7VuE4LWL2ZA2mkUy93ClZTQorRicK6jh44JdCI2dzBGnt0m9ZOUV+zC3f54z9Uege2T2F9PV+2xh37NJxpNNQ78LjbKr3nL5yAi5KFV4G2M55mr1Y3b3292n+5U1DncylMeLOxwwx21muqYNV7UbBU+oB/Sa7FohCHb/go6NSz4JXboXOnB0UsKBcIDCk/CG0DlstXczzHJBaAjurmbaSd2A4MGMz429N6MY8N7fpd3BodzC+B2At4Es5YtXTEPIcbSwgt4IE9DAJEe9UdL9qSXkUuDSBEGLcoQ==,iv:+VhloyxrzIggmtquRKe3Ehe/gRFRRUAnejRzL9WbW0o=,tag:ik5FUlW37Czr9RJmBUIUkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-01-29T17:38:39Z'
    mac: ENC[AES256_GCM,data:MMzaU+xw9yHATfGs8vbNpr+1TiKxCXKhL0ujg5PRS0z0ezlPmKvMSsrqSVoQQnwMfSPimwvoJXEE9TDU9/dAwxj3l0kxNidl5pdQV7sXxsOXdnsNVFEgbFOfsvbNxqIEIwuaHI+A86f+XWv47drNergVMEjgIX6cS5TXzFr5OeE=,iv:AmRaDHiVnWoWKoCnDF+3yKq1xbtWrnvI+Dy/HUoSkSM=,tag:KVv7WJ7PqYqdschfuuw1bw==,type:str]
    pgp:
    -   created_at: '2021-02-28T16:50:54Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/c4S0tk/K3SAQ//TKEcFhADd18FJK+wVOKtuWoXgW9hQWN3tQomwvwCjuNE
            z5oi/rDM8mQAv5WRjI0L74RE2or25ZEItWA5gnjmNVBU0E0vU7ifSmdAT8ImWNtu
            NK2IkKOFa0EnSb1G0dzOELAYTJj9nQ/VVbuJvDIWlTJyZC4yM0NOHVJDczpxKki8
            5o1MGOLUInou9o8KZv+wwT4HcoE+7J0H5cuvNZAqtskAdTfZbZ5QxfTEN7XlgiZQ
            vF6ejCk/aiZSBgtpfeKJQPOWrm4ynqy1ezChuuSKnvgR66DULg9JcAJYlWL5Ps96
            y+K7VWKzdnYOJnwjz3hv11csiYCvOMes0GPjcdSOyWskaCxg/hHeEXcuyftcfMPP
            YeC5fV96NErtgoH5KCBOMUoWg43RFmqnN38sKgTGnb2SmwUZJIcr9/DeoWxf8LuT
            r8LwFJMUbaTlg6mIpKSsQMid0ZmX9oBg/405SxrXvaQKrYlu37XdYvc1ouW0xJRV
            CqvK9SnR33zmLkxJn51wwA1zSFry7yIDGHFdQPnOir4ftQkX1/da6fKMAGt1COsW
            y5UZAcQTShVaBymIb7Wndo7Ph1feMDvR5d2U9QCBFX8F8jSWnEBgBCznmbXUpu+p
            Za0NxrgRgGSPQQQKjc9yiPVbl0FPdD5mSiYOPXbGBwDzLnNDG/VhPieyXyM//iXS
            XgGBRvO/r/QiAHE6yYZS9TU0fhMGdcYgp122ZGYN9QfNaCGJFodphF5/8WdrvX5x
            18yPhlS7IjWk+528/6+IYUR2Vg5aBo5h+hlUitru+IIIRiPj26lr+JnIonolVJY=
            =fGFM
            -----END PGP MESSAGE-----
        fp: 68C22EC0B876AD33C4E38260C60D53073AB48D32
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
