apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:BQE6Xnp2ahQulS4ThhwDUoJmYsSpIwZL8U1cql1ZNr8RNRIIHpe8tyIkw/TApVjhfbx6NFFEPP8LL31eCyG3gy9Co4lWa9LzPJq2++ap2btWe0JE9Xm1osfKVHA8aF6yo/OmYEA6DigLQm2nWgIfTbeSWARF9Uul83ck/XiefLvKyvy5wn11PDCd0thhhVicj569pQ+NoNNpGVyEOnp7hCCS3dMqZUv+uEqY/Q==,iv:NNrAK9KG00rYJhMonp8d+RMQf46G9BIGxGpHBdEn4MA=,tag:9PdnKv0VRDr8MTMoS8XHQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-02-03T22:14:47Z'
    mac: ENC[AES256_GCM,data:v/N6SI77Luboj8yxHEHM1x27aRM5fK64vYKe5YG5mx3ShC+4v3DsJK8l3k0S0SHm5DxeD5p0c2ibHJRH+N6cv/NWYH6tH/qK4nquoSx3OMaq2T6hsw3+I0e39gYNTXBkijTiOustx3Kax0LB2H270n0TLY1f0L883uWcp3tcI1g=,iv:Qsji6yJ+3dj9M1E6e7KZSLH3h+HQv0AloagaBYJ39Vw=,tag:6L/2QviST/tFFfgM/WmhRg==,type:str]
    pgp:
    -   created_at: '2021-02-03T22:04:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx4+MHbVV2OiAQ/8Day6rpAUWkaMIJEVJlrAzz9J45cfsqaq0gNQSXxbH2jy
            licezwgCOpH8p8QV0WHc9UjDWb5rcfhtuX9vm5Ezqi5aW5/7YqNNyNeB5XOr1OLu
            dpuXo7h9MB3+8CfvuIj5fFNwab3bK76srDJb6B4xg+mbP27I8K7UCryJzUfgT1Vs
            kXMJNw2L+chWVahiKgBQGzEpwbMYo6q3+iA/3rM2BQG/tpaB0g70NIAidpdopIXF
            gj16ekoTYTo08+CaVOOcjeeUO/3XfsBSlKbQw05alB1nyGv9M8osmTElQEcb0nGQ
            XHoSTNpX16JgjZ8IQvcuDgzYp8lEPN1kHWMDis0gz1HH8MH8GoWojT4excGoqeI/
            nmuAtWnvtnarBjOAtbYLoDbBDQPf1dU/hvmB6Ey+GgyQaG24WYFrLwfszZYJ+vhw
            s+d5zbA1hZza7S5NtdlwdHooICd44GThnDIj0xGNVWQhSP8hVnrGBq49mqZs870b
            53ROJl1lqwvnXHTRfLfG4a8eQLIgDVR71eYKsijbLhym3POU37kDPmu2roB9Vbr0
            essHYYWQ30ORJfgbNNh2zGx3Yl0p58l5Ezk9hdC6sukFHVobpW9s0YxzjITomU5F
            E5FuOT52k3U7lRzUgUMi0WxNLzpMVETc9B2FXjpcfS+1ofuaURBwgCWPbxr05qXS
            XgE4zTQriJNv0vYu4v3aDjtIgUnqFnx5+tojCze3tdJPbAu7Po6kA0M4rEY5oFvD
            xjD5ABzczZBGlH2t1vJUPR552htFW+lfLeGGXVNFI/2JkCT9Xk66vfoFCe9RWvk=
            =xOMT
            -----END PGP MESSAGE-----
        fp: 4F7B17D8DC0EB7F9B21AB8E484F38067748779D5
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
