apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:opMMKFWjMZplX9AoRLvdj0KjzraLLkyBd7yRq+sU/gM/X2hRokQe+CYw6zHW7WMT4g99aLIE/P+sgfJQ/uCFHzY5Q8YWDfxSFVzr83SlaQ7ASk9CiMl8WCNk3b2qZbuR/WLN+eSSzG2NgDitPxzaxbFOZekl4X9WbT49J3SghExURsnkQiU8cntP2JUoqTQm8fMpiM8cBHdtvn2oV5BeR6jYPV/rW11DhFxIC/v9ySND1p5l7zBMnPxzvJELvQuctwtBIs9RZd6xkK+E73tbqucaJnyLITA1Zc0qGKHzuSCRVaeQVpmU+pW5Sy98FovkM/9o4n/TDI72SEXQqI6VVjpcddxDUYl3e9BVXccBaL532+SrvRRXw7nFcpTZAuG/0uUpGWRmiC+ifn2kWkIDCtFPWy/VJaS15OIBsYtujCbEXSVLeYva0StX1EGhIdZQdkyu0AD2d//rf4oy6VUo0bVHefHyyTEeo7MUie95ILDGQ556cIWzCiCyHWq/dt/lEIgnS49OzW3Afg==,iv:V1a+pQUOozUkot+0xrcc1WuTjqAM4bQGX/fXDy3u7Ec=,tag:9XMkH3Njh79fX+/ElJLPWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-05-06T18:40:24Z"
    mac: ENC[AES256_GCM,data:aHssXEum1Cj0v/umeTdfnqGVJYpOhgq+Vpkji1hEa9PITXpe7HUtCS9vhXa8fHuFfLqpD26IuZj456xzzPvu635NXFbzXq+BxrCIlzAeyVnkZKT8meWW7CS2CyFUSGT8BJbQhCyUkRSC6VHsXko+131tw/2q9Ifb7m6HxzDmAVg=,iv:tXq5ZQYnmlR4rkroQQZLeybT97u0zvW4MyR4LeAYOXs=,tag:6PrniPESZz7f7nNLJogLfg==,type:str]
    pgp:
        - created_at: "2021-05-06T18:40:23Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4srIlhySs1IAQ/+Im7kd0+Ii1AVchpGsgjReGKJUAnIYstaa10mPcXoIsC9
            R3cn7btnjfmkO6PBE5zD/qHLhVZfMJoq4R7lhqFyB7NwnKK+pkMXNmG0xlWr4weY
            DzAi0EL3+g/aMV0yoUsaeus77yymd6ZGxs6CSJ2WR6km7JVOJ7ZLmUoDQt+6RE0s
            rDq52rBsXdaDxm3GJstQ2tp5+ClDVoXI3ROWOoY1yH4hrpIaDOrL4eTcykUc6cln
            qB/dqSOMCCDulAm25VDRdbDc86wDAK+YRm5gM6sSC9K7eu+JIPGMeOeDii07FRrJ
            SbLJg9NTPDLuOupaIUxq1zyatvkKEjbOJTPgmzzbU+bdtnVWzFpV7Zm7YMmP8cDP
            YTXkB42SoQf9XdWtzhmApakG/CGZ+qchtPAlrf4O9lE7V6egvh2wJq8++6KCwAk+
            n4+eg8SXapC+/N0hYy/oKIFaK8NUkoQMbplPcjRvbPEhckZnLMyd68sx5M28j0cC
            NyodzXQOK3z9Tct3k/Bk8GDZI8ulFHs/kquM3J7UFlbM0ywF92LIvUlfDic26Qnr
            ty/jbF/jb0no+LCj90qNUfYtnUb1qEesggCN3im7/fnfXTj+MpGEdyWuiWGwuxyb
            +k93dSO+1JHFHC3g3mCwNNGTCABW6sfUJS4bZCtO8mJF1KcnDsyYBGSVOxsHVNrS
            XgGEy6h4E34IkEoynS0iv8zRBwmybSLWsVG4xCBBTUkJq1pPZRDxnKGoBNBcrM/r
            sAxfT4iIlYd1+ll6JO2J0lznFAyML+1b2L21PDp/IS7F6PGBArqVslMGd+HI87s=
            =6k9C
            -----END PGP MESSAGE-----
          fp: 9776ACAC5A65B3F4CC67993AA8C5CE2E76884D21
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
