apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:nvl0ym3dNFp+IMmcgt2qCs01i4HM59o9Tlhdryp87+q6neGRUYpUudByGrpeqs5SQ0eeznPhNVoHZDxraELsjwhxpwxVUsPXJ2onZh+jIHXU1IPDF23MBObcLuKUwbOMY4xKgL4/F+q2/X3UcbQnJbhHD2QFaatv87NVzTLOds53RcIDkVjWOzItTbEIl6LN4TyStKISxMbSI6XWVlxHYkSwjPPrkXhhl/IA7Wd20aiEg5kPlCWu5I/lxg1G0Sc78+/errHffSHEA6+XFyi2jkKCsRBFqv+Fe7/iZOKc/Xb/ndHaEahBXaJbs7xJhU82yFu7HXl9ECYVHZj3a2QRRvJX6oSTSWBcEw+rBxkgmJihCq+5tXkOL24ZOBDmU3LGliHlc5bhso2JiGl0of1Yc6gCYjlGS0hu8KzGa+B4xWsAO6nGTjSpzt8MXqfTCkbiXCzT8ULseyuAyw==,iv:+5tVAGnTfCxFKUWOc1u8JX7QnGtAnkDHu5LG4Wmi4mg=,tag:cJk37dqqTrn0+Gnqcip8qA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-16T15:24:17Z'
    mac: ENC[AES256_GCM,data:6g97df9OYgJNm6Dx27alpFYeUvSv6a79s5OUwZSWPUtF0QiZUIOlb37BBDAGcxdkeOcUK/vnKMOl20/eaN3GAbFpb0XDxKqsKVLcLFZZiAKA09JXdeSZKmQCEDRge4tykpsB6b7dlsO5iAKMY+1YJaO5zuHnyFmna1ZS9XZrtCg=,iv:oFc2XVWZiS3rAs4Z6EgzE/F5YcVTHHsavz+UYa3grqA=,tag:ZeabHPhNcag44oqqc/UmNQ==,type:str]
    pgp:
    -   created_at: '2021-03-16T15:24:17Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA93W3Fi3CqSYAQ//eQ94JHxhPdZ16W1/ZsXAdHoEITCTwk2qdzlb6T9jkNGi
            XWZs5ukMKVfLRBNe2LB2xlQF6zkZN37Wl60kZq/LRPkxHreK2RJjJiZKIDzkT4rE
            X68hoOI5g4lQExc0vdybNbYiR84HVf2I0XLWQphAKk6E1cN7fOE0Y98F4wPbGQB8
            lps6AkJoGGEQlzxEAUHSBE4XZaxW0PACKS1yQAsv/4x0HExTZyX0LI/42gma9ygF
            sYM9fhwR6LFSJlG6NHT9u4sUz06ZnePHtU/nVLJRyGUHsks4K7qETZlLiwKsYQzB
            6YpZqPaM1MgZCSIFAB/oPyLOToU8NHy7XjFBsV6ew6PM/oUiW4f5IEcpRHtF/gD4
            sn/vQsZP1Rf6GmzSKjHhav5JmSxIOBoPJgswqtalwa+7saZsXBQ7OCToFpPp9AOt
            0AowIPEgoeQIc9IDM1W+oeKqERCmRYB5ma89uqtBp08VUkQy1G74wnhQjtyubzMP
            Aq3Lug6E1n5KVsejRqWHMRBc4TINoJM/Nj5W1sGAfJgt0VK5nQYcUYRKWZysbmhZ
            qsDjYVqCOlFn85be66enDn52ui3LoaLIdH7Djawm+2owPrCmZLTPJJtHv0kiBceB
            JfsLPJ5BEvTtcyfwSVxTWxZcOn0HIpJiXpaBvSPG0/UDo8tNDBLX8tgnVR3js3fS
            XAH8kFCsHePm3ToDoZJOHUG88yepGj9H6US4r8nQfFKLW/XI1R8maTuIbXb+oQqj
            2tmuiBdKiJg8s01/m0ewX6nZ/UmeBw3JWnPK2bin8laAHtmoKEnnWnre+19Y
            =ooVj
            -----END PGP MESSAGE-----
        fp: 41BFF8BAF2586039F6293D835A2E820C25FE527C
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
