#hostname: bigbang.dev
#
#flux:
#  interval: 1m
#  rollback:
#    cleanupOnFail: false
#
#clusterAuditor:
#  enabled: false
#
#gatekeeper:
#  enabled: false
#  values:
#    replicas: 1
#
#kiali:
#  enabled: false
#
#jaeger:
#  enabled: false
#
#istio:
#  values:
#    kiali:
#      dashboard:
#        auth:
#          strategy: anonymous
#
#logging:
#  enabled: false
#
#monitoring:
#  enabled: false
#
#twistlock:
#  enabled: false
#  values:
#    console:
#      persistence:
#        size: 5Gi
#
#
#eckoperator:
#  enabled: false
#
#fluentbit:
#  enabled: false
#
addon:
  minioOperator:
    enabled: true
  minio:
    enabled: true
