# When updating the version of BigBang, make sure to update
#   both the bases reference and the GitRepository reference
bases:
<<<<<<< HEAD
- git::https://repo1.dsop.io/platform-one/big-bang/umbrella.git//base?ref=minio-operator4.0
=======
- git::https://repo1.dsop.io/platform-one/big-bang/bigbang.git//base?ref=1.5.0
>>>>>>> main
resources:
- ingress-cert.enc.yaml
configMapGenerator:
  - name: common
    behavior: merge
    files:
      - values.yaml=configmap.yaml
patchesStrategicMerge:
- secrets.enc.yaml
- |-
  apiVersion: source.toolkit.fluxcd.io/v1beta1
  kind: GitRepository
  metadata:
    name: bigbang
  spec:
    ref:
      $patch: replace
      branch: minio-operator4.0
