# When updating the version of BigBang, make sure to update
#   both the bases reference and the GitRepository reference
namespace: bigbang
bases:
- https://repo1.dso.mil/platform-one/big-bang/umbrella.git/base/?ref=logging-sso
configMapGenerator:
  - name: common
    behavior: merge
    files:
      - values.yaml=configmap.yaml
patchesStrategicMerge:
- secrets.enc.yaml
- |-
  apiVersion: source.toolkit.fluxcd.io/v1beta1
  kind: GitRepository
  metadata:
    name: bigbang
  spec:
    ref:
      $patch: replace
      branch: logging-sso