apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:0TuPQaw0zC6IT0yekhYkjLE6NVkgKmozsP0qxbZstmdzm9MvN6Iatcop5R5IMti02UIvnkJYi2ILC/9rJQWihfnmHZL3EdmoEUxT,iv:IiWfJtgTjsUWLpK7DpLNF6uSrKmWOy3Cjv7jdhYGQ6w=,tag:is0q6wyt9PvtH2fOpgvojQ==,type:str]
sops:
    kms:
    -   arn: arn:aws-us-gov:kms:us-gov-west-1:927962728993:key/f131e19c-a804-4185-b75f-69b995eb9e6a
        created_at: '2020-12-14T22:05:42Z'
        enc: AQICAHiBokhIqRyovOZILp3cL4ZLeOMUIKZsOV08m7PNyQevrgEc7x/D/9Ew4HrGdCyk33k2AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMn9QTdoKFw4D2wcQJAgEQgDvzOYeD5JvMjA9KtrprhLgqJei+QzTo1SVyMc5+IYP8A3zQHJIFfGTOVpIXeeuAovbfDqAa/+JlCgHiyw==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-12-14T22:05:42Z'
    mac: ENC[AES256_GCM,data:RIeQVRonPQ9Kqp1Wgd/JdPntyG3R34zn/2QPlPtxMfy6GKBJTqeE5VOgBk8ye1IL+Iatz7RrET9QmTS5jvXEn0fSjYK/2updGR0tNUpM72EVYrQIpmVe7qugT/a/cuQzJ3PDTfH3p4djo5k3t7FTB7FLqKSjfT8UPru4LR84x6c=,iv:7KK/21JkVc2JrhxrcG1La34ZHHUo0Dc1MU/ZWb5uu7w=,tag:UU1uZbibodLmybMF0JNU9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
