apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:2xS2tIC2tt0PdlGf2taZ3ofdEKJTdTUHfJmSyY07ez/jB73ewTWf33SsEUK31hLyveHDpoPnEw+qvugENq1mKu8rq1W68Ok4Hihvt8jnqN67uAHy5E9yynTchivRK3xS2XHNSqH3XeJrRS2s8RQ3FeFsM7Vn0bIGEnfkxqiVGB4kw1UsGkZADj0YqsMaG/6EgByXY+I1VlkYuwBedSA45s9vNAtTxkRpYtdXkpjUisD40ypHjzZRQBZUEMu2uxUtrDFCyRa/kLj9YMiwQ9BYRrTdXK+82BIvvjHMi4YPGSh6NdA2dlr6EyD2vQ7bvtZs/WB2M2KnFYeJlaHjigV9fvmNFwWVyLXYGT9dVVrIUrJ978MaJQb+gx1K2GgH3HC/ZJB9lYvudE0KQ8RdGunh8Rf+6cDs3FfysnwckLfLOaA8Cz+pTE7O+e3jZZSndjSEGF2vZNXXfyF3mXTowmr/TjI2XvSQo9eU+RqGsJbEAfbbr/rW4Db8voixcfVTL0EeTuu16whY6b46PJOt,iv:Hx9AUjJtSVOL6PC2DRA+Jk2fgrG8nvlIEamK0UN1Ru4=,tag:3G3AY4lfwE3cnS+8/SBkeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-02-23T18:05:06Z'
    mac: ENC[AES256_GCM,data:d4DExX42ccTnpNOrpVwIsRKFMtkvgoMTXMd1aWXMqkcl+P7J+wWL+08MqYzNb3/vG16hP4xebfyRVjwOqq7TDnDB9aE49Vp8X5Q1+EZM4yGmZhJ/gO0BKpEc/KHo9PG7VE4itzby9tcmLIY+R+Xq69MkR+U9yw0nANE8cyPeQsQ=,iv:E1v4Fqsc+1muNdvmV5MIAsNad0xE1M0D+pP13LCtlSI=,tag:Aip9Sxx1U7Fnfrz5V7dg+A==,type:str]
    pgp:
    -   created_at: '2021-02-23T17:16:10Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0kNfsgtTK76AQ//XXuuVpaw3vr6Lol8U6fedIaOq8Od5UmsReZ07YZmumZ7
            z11+Lo3OdkZ6Cc4suvz63f8y5cjROfKWRxWqZ4OTXbs4HK7BsyLU5Zco6RdXv3HU
            nU+sfjE/ALsVlnttnJtomvWRXtifMTDNSmVtLiiBppcgU5Hy/rgO59jEfsG7Fecs
            icWtv51Ui6TYJpMjDN4km8BpcKM9GsAzqmuAuiZK5E40DJtLLpnnDsDdeHwvcX9U
            Wn3x5vQmKISg7TpGol5zl4sD8qHKjFh8OXXUvi9dC49RQuffyesNp1kVef95vqTd
            3xNGhIkpomORkWo3w2mDe/T6xriskUGwnGvIgbEhLlLVKvO3ogZnSRKsBT2oZaGj
            yKa5che5rnqWvg/16J0qe1H+enQcpvCVygUw7yMuoCGfl2EmmWfs4096yUq0WFwl
            7aQVXg9vQNa/0c7hSteOHn5tKIM5Q+kAgOTvvro5DVkJnwE03X/aJtIx0pFFLHoj
            QcHcoNbHnQXqT/F7LbE/FdAvmgDncGaZeEUQUDEIFtesxXecA9gMWYK4XXAfoppf
            L4DX3vN/QuPCqTmbnuiiTZmgRfPH7ZR9R0mNIwn6JEg2ZWmE30/G/S2LiW7Huokx
            LSuf/fhyMWjgbtgIQhsmyPEf6C5snITjrOczPzFpN9bE+X2SS55x4RO56X1Hsm7S
            XAGSV7kavp4usmep4Iv9UH1euefnW9GV7MaPdpUEAoYbWtvyPEDwF+laYVoinxut
            4CQOal8gC1vQsBDjbRJi/LAbHA7YbVeItRN28E80wdGqj5FZQ6xOPd9Wctbv
            =ENDq
            -----END PGP MESSAGE-----
        fp: 05C6221BE32EFE6060363B13CF4D2B3519F8DD6B
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
