apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:5MuZVcju5wHBohVoBy8sGL1iAKgnKdTxzbGq1NUQ3LFHm0vc6WxQZcKv/kLy+xbcDWOqEczmR+4cY2HTCsatXmaa,iv:nxOrBl2GZN74FRnT7kFKpIGy0fnN9BXTAvLqt7b3lZk=,tag:HPewdfilS3eUzKoFL1HYAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-12-31T21:58:58Z'
    mac: ENC[AES256_GCM,data:9cw4TEysRzdTygC1L04JbiaEBuoDPWFg5FeC2KfaRnxFXm+HppWgoe6rX5o6qvTCGS2hdVxBK5WxiJPYtnHDDo5xORY4m+73f3X90FvsGb1gNbIV3KYQon1iDq+w5znVSytd2F2izPGjvEL4x/iwwYgavSaLvNn1H07h6Us2Oks=,iv:Djc6qXjvCPSS00yYTQsuTz83iYLVfIvo9IFu5gOH9/Y=,tag:rBX0t1CT2uXg2rM78HdOew==,type:str]
    pgp:
    -   created_at: '2020-12-30T20:55:54Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2B54dND7BORARAAqgn+4kDUa8z2KVBzrF4qOngRPAI/ZAEZCeDvUa3JPAUI
            ixiQDZf1F3EO5/pYn8bGiw1+LCes0MlUL6BLYEj7IiFRmxO7Ab56hUKTnoA4+gh9
            FIOf4OoC4XF37Lh5zvrcczCDN1IGbOj9Cg2HXzCHpZVK2lj3z+SxAx2692IwAPL4
            NMHS0pMLQNUsDs5wiUcVDr6er4Su67zFi2uQupXlXVtgfaodW9nCiibnIPigh2Et
            BOjmoK/rspz/YeojqJyp8WmUBWr3XwIJrfihq1Wh/Zh5PlWEFpUli4P3FKLtOr/v
            Xu4uCqcwYFLl9qgiRGDU0396C/ZRW/YnCHnXGN9joI6ReJL20HxtNh60UHtksGku
            5awKhaQjo8IGBAjIj7u9ddUHNjkix+pJbljMFF6s6vbYusClKefBq05VtjIwWqz7
            yws5nqdL5fBl1+DQJnyrJblO4XWYhx5ZWSo1ctwdA+y7L3TgWRr4aHwrXzVCE6e7
            +em4wbzy7zK5GNP4fyDfvRepx0RrRd5J1ypxEYxy69AX6wKV3g5ZloR9jOzIvUrP
            FzRQA/jWZZYtVfsXFrousMAtlcEFjEJoCq8X/hlGEwdHvFU8htX7giPC59b8Su7t
            bCClIJVt1s3gqsxPLFk6LqC5EyR0l8nCOO67ASM58+ebj8ZnpesVMdHM4cyUd5fS
            XgFTnULTHBYtL0hNPHryhjU3j3QXCLTZrZGjK91c/at7USEyzrpbAxrgWbrfsonX
            JUhLE4/Nv+b88emt4FxsvwZiYO+kiGOEdQvdA30QwpUQX4pgR/ywlqardyol7TI=
            =nrwG
            -----END PGP MESSAGE-----
        fp: 9F4CD9A4E06605F8AF97721CF7FFDEF927CD7F78
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
