apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: null
sops:
    kms:
    -   arn: arn:aws-us-gov:kms:us-gov-west-1:927962728993:key/f131e19c-a804-4185-b75f-69b995eb9e6a
        created_at: '2021-01-06T17:49:24Z'
        enc: AQICAHiBokhIqRyovOZILp3cL4ZLeOMUIKZsOV08m7PNyQevrgHjVt+8RCrMbNy9UMSRQZ9zAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMZN+TOpdLcmUQhN5PAgEQgDuTW357/mii77Isd/bNarGr9zPGAuC5HffpSUYKxhz2DXcFJINlZxF7z+v8xPmzRPrbt/UJzyBxdGvuhg==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    lastmodified: '2021-01-14T16:22:55Z'
    mac: ENC[AES256_GCM,data:Y76p9I2QMwvfHPXca3qYRumNByjibbZec/zYuC5zyEweXEk1CGpOmyejyh/IlqAfbyklnGuA9MxlAQNDwDeB5Uo6Qw2wzCslnjFKDaFseYa8GUlwSkgHiYroRLDf/mTZun4Y832zAGz/XEKwgbmdBHY78jFunvKYzSqSpbUHsqE=,iv:cnB3/FovptnQqPhzWYt5YNWpnOmZ+DkKdhxLRPL9Mmo=,tag:rBp2ONd60oC0XmLowqgh5A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.5.0
