apiVersion: v1
kind: Secret
metadata:
    name: common-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:xLlPGTrnBXQq8ZzT46JHYBj5026f4OSyxdlZ7X5fZ8h/w4eREaQ28+v3IIn45A5Fol0QIfGnaaSSgfn59WwpLYQd,iv:L+FGJo5g8UzBS4hhwS0c1+VIQcgTiuFtfTdCJgL0ezM=,tag:XGNFh4gnm8D3dVe/JxFBlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-01-04T14:53:55Z'
    mac: ENC[AES256_GCM,data:eoNddpNxMJaH+tPPOWrz1T26jMKITf9McIeth9FSPbykJ40F/Hqrxl/EJWRI7cATu7tWKjySDa1YA/CuQRnwFeoZ/2+nOxzkdyige3CQuB//BRQBWkh4Uq7hqGrvmsquKoa8USzxYcRjfgFlUI8raAhBI+DVKbM3jwEi4CIrTDU=,iv:ITYQ66a5NVgTB9AAW9W/LNT8UhWJP5baTk3tnizJXQo=,tag:h2L7UDO3rPC+e/1wk+dXTA==,type:str]
    pgp:
    -   created_at: '2020-12-30T20:55:54Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA2B54dND7BORARAAqgn+4kDUa8z2KVBzrF4qOngRPAI/ZAEZCeDvUa3JPAUI
            ixiQDZf1F3EO5/pYn8bGiw1+LCes0MlUL6BLYEj7IiFRmxO7Ab56hUKTnoA4+gh9
            FIOf4OoC4XF37Lh5zvrcczCDN1IGbOj9Cg2HXzCHpZVK2lj3z+SxAx2692IwAPL4
            NMHS0pMLQNUsDs5wiUcVDr6er4Su67zFi2uQupXlXVtgfaodW9nCiibnIPigh2Et
            BOjmoK/rspz/YeojqJyp8WmUBWr3XwIJrfihq1Wh/Zh5PlWEFpUli4P3FKLtOr/v
            Xu4uCqcwYFLl9qgiRGDU0396C/ZRW/YnCHnXGN9joI6ReJL20HxtNh60UHtksGku
            5awKhaQjo8IGBAjIj7u9ddUHNjkix+pJbljMFF6s6vbYusClKefBq05VtjIwWqz7
            yws5nqdL5fBl1+DQJnyrJblO4XWYhx5ZWSo1ctwdA+y7L3TgWRr4aHwrXzVCE6e7
            +em4wbzy7zK5GNP4fyDfvRepx0RrRd5J1ypxEYxy69AX6wKV3g5ZloR9jOzIvUrP
            FzRQA/jWZZYtVfsXFrousMAtlcEFjEJoCq8X/hlGEwdHvFU8htX7giPC59b8Su7t
            bCClIJVt1s3gqsxPLFk6LqC5EyR0l8nCOO67ASM58+ebj8ZnpesVMdHM4cyUd5fS
            XgFTnULTHBYtL0hNPHryhjU3j3QXCLTZrZGjK91c/at7USEyzrpbAxrgWbrfsonX
            JUhLE4/Nv+b88emt4FxsvwZiYO+kiGOEdQvdA30QwpUQX4pgR/ywlqardyol7TI=
            =nrwG
            -----END PGP MESSAGE-----
        fp: 9F4CD9A4E06605F8AF97721CF7FFDEF927CD7F78
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
